//
//  PopularConfigurator.swift
//  FinalProject
//
//  Created by Ерасыл Еркин on 16.05.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PopularConfigurator {
    
    static let shared = PopularConfigurator()
    
    func configure(viewController: PopularViewController) {
        let interactor = PopularInteractor()
        let presenter = PopularPresenter()
        let router = PopularRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
