//
//  PopularInteractor.swift
//  FinalProject
//
//  Created by Ерасыл Еркин on 16.05.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularBusinessLogic
{
  func doSomething(request: Popular.Something.Request)
}

protocol PopularDataStore
{
  //var name: String { get set }
}

class PopularInteractor: PopularBusinessLogic, PopularDataStore
{
  var presenter: PopularPresentationLogic?
  var worker: PopularWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Popular.Something.Request)
  {
    worker = PopularWorker()
    worker?.doSomeWork()
    
    let response = Popular.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
